### ISSUE TITLE
Ten or more LineSeries with 10k points is very slow

### ISSUE THREAD

**Issue by redcurry** [oxyplot/oxyplot#1358]
Creating a simple plot with ten LineSeries, each with 10,000 data points is very slow (both while resizing the parent window and while tracking). Interestingly, setting the InterpolationAlgorithm to CanonicalSpline improves the performance (it feels at least twice as fast). Is this slowness expected for this number of data points? Is there any way to improve the performance, especially while resizing the parent window and/or tracking?

**Comment by VisualMelon** [comment]
Which platform is this?

See #1286 for some discussion.

**Comment by redcurry** [comment]
I'm running this on WPF (.NET Framework 4.7.2 on Windows 10).

I looked at #1286, and I implemented the aliased LineSeries, but performance was still slow and, as expected, the lines were very ugly.

I ran the Visual Studio profiler on the application, and the potential causes of the slowdown are "Layout", "Render", and "Garbage collection." I was very surprised by the garbage collection because I didn't think anything would need to be collected while resizing a window, as if objects were being created. Looking into the layout, most of the time is spent on individual Polyline objects.

**Comment by Krusty93** [comment]
I am trying to plot 20 series, each with 1100 data points and the window resizing, panning and zooming are very very slow. I tried to enable the alias as described in #1286, but it is not enough.
I don't use anything 'dotted' and I gave a try to MinimumSegmentLength property (found in another GitHub's thread), but it is still the same.

Running on WPF, W10, .NET Framework 4.7.2.
