### ISSUE TITLE
ContourSeries produce fake connections

### ISSUE THREAD

**Issue by ShannonZ** [oxyplot/oxyplot#1685]
# Steps to reproduce
For some data, if one used some improper parameters, ContourSeries will produce some fake connections/contours.
The data containing two isolated peaks [attached](https://drive.google.com/file/d/17GJbHztDo0KeYu6HLMI-iC9gBuo_V8SM/view?usp=sharing)  using 

```
            double[] contour_levels = { 0.2, 0.4, 0.6, 0.8, 0.9, 1.0 };
            double maxi = max value in data[, ];
           
            double[] tmp = new double[contourlevels.Length];
            for (int i = 0; i < contourlevels.Length; i++)
            {
                tmp[i] = maxi * contourlevels[i];
            }

           ContourSeries cs = new ContourSeries
            {
                TextColor = OxyColors.Transparent,   
                LabelBackground = OxyColors.Transparent,   
                ContourLevels = tmp,
                Data = data,
            };
```
would produce some artificial connections between the two peaks.

Platform: Windows 10 x64
.NET version: 4.7.2

### Expected behaviour

There should be no fake contours.

### Actual behaviour

Two isolated peaks connected with each other when drawing with ContourSeries.
![20201010100726](https://user-images.githubusercontent.com/7865691/95643219-78c41300-0ae0-11eb-8ee0-5a003b57b9e5.jpg)

**Comment by Jonarw** [comment]
Is this with the current stable version (2.0) or the latest version (from myget or directly built from source)?
I'm asking because are some unreleased [changes](https://github.com/oxyplot/oxyplot/pull/1560) to the `ContourSeries`. I'm wondering whether this issue might be either caused by these changes, or maybe it is already fixed by it.

**Comment by ShannonZ** [comment]
> Is this with the current stable version (2.0) or the latest version (from myget or directly built from source)?
> I'm asking because are some unreleased [changes](https://github.com/oxyplot/oxyplot/pull/1560) to the `ContourSeries`. I'm wondering whether this issue might be either caused by these changes, or maybe it is already fixed by it.

I‘ve tried all available version from nuget.

**Comment by Jonarw** [comment]
Well these changes wouldn't be on Nuget yet, as they are unreleased. You have three possibilities:
- Download the source code (`develop` branch) from GitHub and directly reference this from your project
- Get the latest pre-release package from myget
- Wait for a week or so until we release v2.1 pre-release on Nuget (see https://github.com/oxyplot/oxyplot/issues/1671)

Again, I can't guarantee the new version will solve your problem, but I would like to try and avoid reproducing a problem that may already be fixed.

**Comment by ShannonZ** [comment]
> Well these changes wouldn't be on Nuget yet, as they are unreleased. You have three possibilities:
> 
> * Download the source code (`develop` branch) from GitHub and directly reference this from your project
> * Get the latest pre-release package from myget
> * Wait for a week or so until we release v2.1 pre-release on Nuget (see #1671)
> 
> Again, I can't guarantee the new version will solve your problem, but I would like to try and avoid reproducing a problem that may already be fixed.

Not solved using the latest pre-release package from myget.
Still produce fake connections using the latest develop branch.

**Comment by VisualMelon** [comment]
I can't immediately reproduce this: could you provide details on the axes and Row/Column coordinates you are using?

![image](https://user-images.githubusercontent.com/5646475/95830769-18c3ab80-0d30-11eb-8a8e-f517cc615bd1.png)

Would you be happy for that data to be included in the example library for an entry for this issue?

**Comment by ShannonZ** [comment]
[ContourSeriesIssue.zip](https://github.com/oxyplot/oxyplot/files/5375020/ContourSeriesIssue.zip)
@VisualMelon @Jonarw  A demo to reproduce this issue was attached. The data is just a MATLAB generated data, free to use it.

**Comment by VisualMelon** [comment]
@ShannonZ thanks, I can reproduce it now with those X/Y values.

**Comment by Jonarw** [comment]
The issue appears to be in `ContourSeries.JoinContourSegments()`, where apparently some segments can get joined that shouldn't. This is marked as 'to be improved' anyway. I have an idea for an alternative algorithm which should also be faster - I will give it a try.

**Comment by ShannonZ** [comment]
@Jonarw Is this issue fixed in 2.1.0 Preview?

**Comment by Jonarw** [comment]
Not yet no. I still have to finish up the PR and then the fix will be on the `develop` branch. We might consider pulling it in the preview as it is a bug fix, but this might take some more time.
