### ISSUE TITLE
This PlotModel is already in use by some other PlotView control.

### ISSUE THREAD

**Issue by sunwayking** [oxyplot/oxyplot#497]
This issue occures at line 165 in PlotViewEx.cs.
As my thought, reattaching same plotmodel to the same plotview should not throw this InvalidOperationException showing on title.
Then a possible solution is to avoid throwing InvalidOperationException and reattaching plotmodel when this.currentModel.PlotView equals current plotview object(this).

Code modification is here:

```C#
private void OnModelChanged()
{
    lock (this.modelLock)
    {
        if (this.currentModel != null)
        {
            ((IPlotModel)this.currentModel).AttachPlotView(null);
        }

        this.currentModel = this.Model;

        if (this.currentModel != null && !Equals(this.currentModel.PlotView, this))
        {
            if (this.currentModel.PlotView != null)
            {
                throw new InvalidOperationException(
                    "This PlotModel is already in use by some other PlotView control.");
            }

            ((IPlotModel)this.ActualModel).AttachPlotView(this);
        }
    }

    this.InvalidatePlot();
}
```

**Comment by tibel** [comment]
I think this use case should never happen. Can you describe your scenario, please.

**Comment by HippoBaro** [comment]
@tibel I had experiended those errors using Xamarin.Forms when creating multiple instances of the same ContentPage (including a PlotView) with different data.
Xamarin.Forms does a great job in reusing existing UIViewController to save memory, but it can cause OxyPlot to raise this exception.

**Comment by tibel** [comment]
I have moved the check to `PlotModel.AttachPlotView()` and allow attaching the same `plotView` again.

**Comment by staylr** [comment]
In OxyPlot.Xamarin.{Android,iOS}.PlotView you also need to clear the Model when disposing. Not sure what the solution is (if needed) on Windows Phone.


        /// <summary>
        /// Dispose the instance.
        /// </summary>
        /// <param name="disposing">Is the instance disposing.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                this.Model = null;
            }

            base.Dispose(disposing);
        }

**Comment by omsara** [comment]
Bonjour;
Actuellement j'utilise la version "OxyPlot.Xamarin.Forms.2015.1.889-alpha"; et j'ai le même soucis cité au début; y-a-t'il une solution  ? 
 et aussi j'ai un autre soucis sur cette même version  le plot ne s'affiche pas au niveau de windows-phone ? 
merci de votre aide .

**Comment by BWouters** [comment]
This occurs also in the OxyPlot.WPF 2015.1.989.0-alpha release

**Comment by tibel** [comment]
Can you provide a sample project that shows the issue, please.

**Comment by objorke** [comment]
I added two examples - with PlotViews created by a DataTemplate.
It seems to work on Android, but not for Windows Phone.

**Comment by objorke** [comment]
The ItemTemplate demos works on all Xamarin Forms platforms.
Can we close this issue?

**Comment by tongbong** [comment]
I encountered that problem as well with that code in PlotModel.cs line 772:
        `void IPlotModel.AttachPlotView(IPlotView plotView)
        {
            var currentPlotView = this.PlotView;
            if (!object.ReferenceEquals(currentPlotView, null) &&
                !object.ReferenceEquals(plotView, null) &&
                !object.ReferenceEquals(currentPlotView, plotView))
            {
                throw new InvalidOperationException(
                    "This PlotModel is already in use by some other PlotView control.");
            }

            this.plotViewReference = (plotView == null) ? null : new WeakReference(plotView);
        }`

**My use case is to display the same plot model on different panels and so I would like to instanciate as many views as necessary binded on a single plot model.**

The code above prevents that use case, doesn'it?
I do not understand why the model is referencing the view.
Should not the invalidation be based on some kind of event? Therefore multiple views could use the samoe model.

**Comment by tibel** [comment]
Currently there is a one-to-one relation between the `PlotView` and its `PlotModel` (see #112).

**Comment by objorke** [comment]
Yes, a `PlotModel` can only be used in one `PlotView`.

Can we close this issue?

**Comment by tongbong** [comment]
If this is part of the major refactoring as in #112, then I would say yes.

**Comment by objorke** [comment]
Yes :)

**Comment by tibel** [comment]
Example: WpfExamples / PlotModelAlreadyInUse
see description in #780 for how to reproduce

**Comment by CedreLo** [comment]
Same problem with several plotmodel and plotview using a TabControl and MVVM design

This PlotModel is already in use by some other PlotView control

**Comment by anjdreas** [comment]
I just worked around the same issue by defining the PlotModel in XAML instead of in VM, so the PlotModel belongs to the view, not the view model. I think that is how oxyplot is "designed", since it is so tightly coupled to the view. You might be able to something similar by moving your PlotModel instance into the view and bind to that and manipulate that from VM, or just go XAML entirely.

**Comment by CedreLo** [comment]
Could you detail how to instance the plotmodel in the view ?

**Comment by anjdreas** [comment]
http://docs.oxyplot.org/en/latest/getting-started/hello-wpf-xaml.html

```xaml
    <Grid>
<!--        <oxy:PlotView Model="{Binding PlotModel}"/>-->
        <oxy:Plot x:Name="_plot" Title="Forces" IsLegendVisible="True" InvalidateFlag="{Binding InvalidateFlag, Delay=20, IsAsync=True}">
            <oxy:Plot.Axes>
                <oxy:TimeSpanAxis StringFormat="s\.ff" Position="Bottom" Title="Time" Key="Time" />
                <oxy:LinearAxis Position="Left" Title="Force" Unit="kg-f" Key="Forces" />
                <oxy:LinearAxis Position="Right" Title="Moment" Unit="N-m" Key="Moment" />
            </oxy:Plot.Axes>
            <oxy:Plot.Annotations>
                <oxy:LineAnnotation Type="Vertical" X="{Binding Path=TimeMarkerValue, Mode=OneWay}" />
            </oxy:Plot.Annotations>
            <oxy:LineSeries Title="Fx" ItemsSource="{Binding ForceX}" YAxisKey="Forces" />
            <oxy:LineSeries Title="Fy" ItemsSource="{Binding ForceY}" YAxisKey="Forces" />
            <oxy:LineSeries Title="Fz" ItemsSource="{Binding ForceZ}" YAxisKey="Forces" />
<!--            <oxy:LineSeries ItemsSource="{Binding MomentX}" YAxisKey="Moment" />-->
<!--            <oxy:LineSeries ItemsSource="{Binding MomentY}" YAxisKey="Moment" />-->
            <oxy:LineSeries Title="Mz" ItemsSource="{Binding MomentZ}" YAxisKey="Moment" />
        </oxy:Plot>
```

**Comment by anjdreas** [comment]
The InvalidateFlag is changed in VM whenever it needs to redraw the entire thing, such as when new points are added to the series. Similar to calling `Invalidate` methods on the plot model itself.

**Comment by CedreLo** [comment]
Thanks!!

**Comment by MannusEtten** [comment]
but this xaml example doesn't work in UWP :-(

**Comment by Inzanit** [comment]
This might be a bit of a dumb question, but how come there is a 1:1 between the PlotModel and the View? We've been having trouble in our WPF app, using DataTemplates, with this exception. I've been digging and eventually just removed the exception being thrown in PlotModel.cs line 772, as referenced by @tongbong and nothing (at least on the surface) seems to have gone horrifically wrong.

**Comment by inosik** [comment]
What is the reasoning behind this exception? In my app, the `PlotModel` object is constructed and maintained in the VM, but the view is getting constructed every time the user opens the section of the app, which contains the actual plot. So this exception is thrown every time the user navigates to the plot, then back to the main view and then back again to the plot.

**Comment by JavierJJJ** [comment]
Same error on WPF v1.0
The error raise when the aplication is open and connect via desktop remote. Then raise the error: **This PlotModel is already in use by some other PlotView control.**

>   en OxyPlot.PlotModel.OxyPlot.IPlotModel.AttachPlotView(IPlotView plotView) en C:\projects\oxyplot\Source\OxyPlot\PlotModel\PlotModel.cs:línea 798
   en OxyPlot.Wpf.PlotView.OnModelChanged() en C:\projects\oxyplot\Source\OxyPlot.Wpf\PlotView.cs:línea 153
   en OxyPlot.Wpf.PlotView.ModelChanged(DependencyObject d, DependencyPropertyChangedEventArgs e) en C:\projects\oxyplot\Source\OxyPlot.Wpf\PlotView.cs:línea 140
   en System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   en System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   en System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   en System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   en System.Windows.StyleHelper.ApplyTemplatedParentValue(DependencyObject container, FrameworkObject child, Int32 childIndex, FrugalStructList`1& childRecordFromChildIndex, DependencyProperty dp, FrameworkElementFactory templateRoot)
   en System.Windows.StyleHelper.InvalidatePropertiesOnTemplateNode(DependencyObject container, FrameworkObject child, Int32 childIndex, FrugalStructList`1& childRecordFromChildIndex, Boolean isDetach, FrameworkElementFactory templateRoot)
   en System.Windows.FrameworkTemplate.InvalidatePropertiesOnTemplate(DependencyObject container, Object currentObject)
   en System.Windows.FrameworkTemplate.HandleBeforeProperties(Object createdObject, DependencyObject& rootObject, DependencyObject container, FrameworkElement feContainer, INameScope nameScope)
   en System.Windows.FrameworkTemplate.<>c__DisplayClass45_0.<LoadOptimizedTemplateContent>b__2(Object sender, XamlObjectEventArgs args)
   en System.Xaml.XamlObjectWriter.OnBeforeProperties(Object value)
   en System.Xaml.XamlObjectWriter.Logic_CreateAndAssignToParentStart(ObjectWriterContext ctx)
   en System.Xaml.XamlObjectWriter.WriteStartMember(XamlMember property)
   en System.Xaml.XamlWriter.WriteNode(XamlReader reader)
   en System.Windows.FrameworkTemplate.LoadTemplateXaml(XamlReader templateReader, XamlObjectWriter currentWriter)


>   en System.Windows.FrameworkTemplate.LoadTemplateXaml(XamlReader templateReader, XamlObjectWriter currentWriter)
   en System.Windows.FrameworkTemplate.LoadTemplateXaml(XamlObjectWriter objectWriter)
   en System.Windows.FrameworkTemplate.LoadOptimizedTemplateContent(DependencyObject container, IComponentConnector componentConnector, IStyleConnector styleConnector, List`1 affectedChildren, UncommonField`1 templatedNonFeChildrenField)
   en System.Windows.FrameworkTemplate.LoadContent(DependencyObject container, List`1 affectedChildren)
   en System.Windows.StyleHelper.ApplyTemplateContent(UncommonField`1 dataField, DependencyObject container, FrameworkElementFactory templateRoot, Int32 lastChildIndex, HybridDictionary childIndexFromChildID, FrameworkTemplate frameworkTemplate)
   en System.Windows.FrameworkTemplate.ApplyTemplateContent(UncommonField`1 templateDataField, FrameworkElement container)
   en System.Windows.FrameworkElement.ApplyTemplate()
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en System.Windows.Controls.WrapPanel.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   en System.Windows.Controls.ItemsPresenter.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en System.Windows.Controls.Border.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en System.Windows.Controls.Control.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   en System.Windows.Controls.ContentPresenter.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en System.Windows.Controls.VirtualizingStackPanel.MeasureChild(IItemContainerGenerator& generator, IContainItemStorage& itemStorageProvider, IContainItemStorage& parentItemStorageProvider, Object& parentItem, Boolean& hasUniformOrAverageContainerSizeBeenSet, Double& computedUniformOrAverageContainerSize, Double& computedUniformOrAverageContainerPixelSize, Boolean& computedAreContainersUniformlySized, IList& items, Object& item, IList& children, Int32& childIndex, Boolean& visualOrderChanged, Boolean& isHorizontal, Size& childConstraint, Rect& viewport, VirtualizationCacheLength& cacheSize, VirtualizationCacheLengthUnit& cacheUnit, Boolean& foundFirstItemInViewport, Double& firstItemInViewportOffset, Size& stackPixelSize, Size& stackPixelSizeInViewport, Size& stackPixelSizeInCacheBeforeViewport, Size& stackPixelSizeInCacheAfterViewport, Size& stackLogicalSize, Size& stackLogicalSizeInViewport, Size& stackLogicalSizeInCacheBeforeViewport, Size& stackLogicalSizeInCacheAfterViewport, Boolean& mustDisableVirtualization, Boolean isBeforeFirstItem, Boolean isAfterFirstItem, Boolean isAfterLastItem, Boolean skipActualMeasure, Boolean skipGeneration, Boolean& hasBringIntoViewContainerBeenMeasured, Boolean& hasVirtualizingChildren)
   en System.Windows.Controls.VirtualizingStackPanel.MeasureOverrideImpl(Size constraint, Nullable`1& lastPageSafeOffset, List`1& previouslyMeasuredOffsets, Nullable`1& lastPagePixelSize, Boolean remeasure)
   en System.Windows.Controls.VirtualizingStackPanel.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   en System.Windows.Controls.ItemsPresenter.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en System.Windows.Controls.Border.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en System.Windows.Controls.Control.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   en System.Windows.Controls.ScrollContentPresenter.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en System.Windows.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
   en System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
   en System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV)
   en System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en System.Windows.Controls.ScrollViewer.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en System.Windows.Controls.Border.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en System.Windows.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
   en System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
   en System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV)
   en System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en System.Windows.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
   en System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
   en System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV)
   en System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   en System.Windows.Controls.ContentPresenter.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en System.Windows.Controls.Border.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en System.Windows.Controls.Control.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   en System.Windows.Controls.ContentPresenter.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en System.Windows.Controls.Border.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en System.Windows.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
   en System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
   en System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV)
   en System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en System.Windows.Controls.Control.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en System.Windows.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
   en System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
   en System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV)
   en System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   en System.Windows.Controls.ContentPresenter.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en System.Windows.Controls.Border.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en System.Windows.Controls.Control.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   en System.Windows.Controls.ContentPresenter.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en System.Windows.Controls.Control.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   en System.Windows.Controls.ContentPresenter.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en System.Windows.Documents.AdornerDecorator.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en System.Windows.Controls.Border.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en System.Windows.Window.MeasureOverrideHelper(Size constraint)
   en System.Windows.Window.MeasureOverride(Size availableSize)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en System.Windows.ContextLayoutManager.UpdateLayout()
   en System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   en System.Windows.Media.MediaContext.InvokeOnRenderCallback.DoWork()
   en System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   en System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   en System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Inzanit** [comment]
I don't think it has anything to do with remote desktop. It's like I asked, if you maintain the view from the ViewModel and redraw the UI, the plotmodel is in use because the previous view may not have been GC'd or is being cached underlyingly. Also, thanks for that obnoxiously long stack trace.

**Comment by edvinasz** [comment]
I know this is old and done, but until proper refactoring mentioned above is complete.  Using PlotModel in a ViewModels and dynamically generating Views (ex. TabControls with DataTemplates) is not possible with out having the exception thrown once in a while.

So I though I would share a "simple" hack work around. 

Instantiate this type instead of PlotModel in your VM and the most recent DataTemplate View will be auto attached.

```C#
    using System;
    using System.Linq;
    using System.Reflection;
    using OxyPlot;

    /// <summary>
    /// Use this sub implementation of the <see cref="PlotModel"/> if the view will be declared using data template.
    /// Because views will be automatically generated, and new view will be different this causes current version to throw an error.
    /// </summary>
    public class ViewResolvingPlotModel : PlotModel, IPlotModel
    {
        private static readonly Type BaseType = typeof(ViewResolvingPlotModel).BaseType;
        private static readonly MethodInfo BaseAttachMethod = BaseType
            .GetMethods(BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly)
            .Where(methodInfo => methodInfo.IsFinal && methodInfo.IsPrivate)
            .FirstOrDefault(methodInfo => methodInfo.Name.EndsWith(nameof(IPlotModel.AttachPlotView)));

        void IPlotModel.AttachPlotView(IPlotView plotView)
        {
            //because of issue https://github.com/oxyplot/oxyplot/issues/497 
            //only one view can ever be attached to one plotmodel
            //we have to force detach previous view and then attach new one
            if (plotView != null && PlotView != null && !Equals(plotView, PlotView))
            {
                BaseAttachMethod.Invoke(this, new object[] { null });
                BaseAttachMethod.Invoke(this, new object[] { plotView });
            }
            else
            {
                BaseAttachMethod.Invoke(this, new object[] { plotView });
            }
        }
    }
```

**Comment by JohnnyHerms** [comment]
I also commented out the exception being thrown in PlotModel.cs as mentioned by @Inzanit and @tongbong.  I'm using WPF targeting .NET 4.0
--

**Comment by xcosmos6** [comment]
edvinasz's approach solved my problem. Thank you so much! @edvinasz

**Comment by fuglede** [comment]
Does @edvinasz' solution cause any other issues elsewhere, or could it be added to [`PlotModel`](https://github.com/oxyplot/oxyplot/blob/d9148f7eed2455ac4abbfd2975972d0c1f799997/Source/OxyPlot/PlotModel/PlotModel.cs#L791) directly?

**Comment by TFWSoftware** [comment]
I really like the solution offered by @edvinasz but I had a case where I couldn't use a derived class from PlotModel so I created this extension class:
```c#
public static class PlotModelExtensions
	{
	public static void AttachToView(this PlotModel plotModel, IPlotView plotView)
		{
		// Because of issue https://github.com/oxyplot/oxyplot/issues/497 
		// only one view can ever be attached to one plotmodel.
		// We have to force detach from any previous view and then attach to the new one.
		MethodInfo BaseAttachMethod = plotModel.GetType().GetMethods(BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly)
							.Where(methodInfo => methodInfo.IsFinal && methodInfo.IsPrivate)
							.FirstOrDefault(methodInfo => methodInfo.Name.EndsWith(nameof(IPlotModel.AttachPlotView)));

		if (plotView != null && plotModel.PlotView != null && !Equals(plotView, plotModel.PlotView))
			{
			BaseAttachMethod.Invoke(plotModel, new object[] { null });
			}
		BaseAttachMethod.Invoke(plotModel, new object[] { plotView });
		}
	}
```

Use it simply like this:
```c#
    plotModel.AttachToView(plotView);
```

**Comment by luis-barreira** [comment]
I'm using Xamarin Forms and I have this exception when running on UWP simply by navigating away from the page with the chart and then back to the chart page. The solution provided by @edvinasz solved my problem.

**Comment by LakMoore** [comment]
My problem was when using the PlotView within a CarouselView.  Many comments above state that they are using DataTemplate, however it is important to understand that the DataTemplate can be made to do very different things.  In the below example, pairList and singlePair are normal Views and tickChart is a View whose content is set to a PlotView, the PlotModel for which is constructed each time the PlotView is constructed.

    var myCarousel = new CarouselViewControl();
    myCarousel.ItemsSource = new List<DataTemplate>()
    {
        new DataTemplate(() => { return pairList; } ),   //this view can be cached/re-used
        new DataTemplate(() => { return singlePair; }),  //this view can be cached/re-used
        new DataTemplate(() => { 
            tickChart = new Views.TickChart();           //need a new one every time!
            return tickChart; 
        })   
    };
    myCarousel.PositionSelected += OnPositionSelected;
    Content = myCarousel;

**Comment by MatrixRonny** [comment]
I created a simple project that generates the exception using DataTemplates. It should provide more information about the problem. Basically, PlotView.OnModelChanged does not get called when changing multiple layers of DataTemplates. In this case, the View containing the PlotView can be displayed again only after the GC collects the previous instance of that View.

Here is the code: https://github.com/MatrixRonny/OxyPlotApp

**Comment by IronLllama** [comment]
Hi @edvinasz 

This work around is great. Do we have your permission to use it in our code however we wish?

Thanks,

IronLlama

> I know this is old and done, but until proper refactoring mentioned above is complete. Using PlotModel in a ViewModels and dynamically generating Views (ex. TabControls with DataTemplates) is not possible with out having the exception thrown once in a while.
> 
> So I though I would share a "simple" hack work around.
> 
> Instantiate this type instead of PlotModel in your VM and the most recent DataTemplate View will be auto attached.

**Comment by edvinasz** [comment]
Yes @IronLlama.

**Comment by IronLllama** [comment]
> Yes @ironllama.

Thank you!

**Comment by Sahhary** [comment]
> 
> 
> I just worked around the same issue by defining the PlotModel in XAML instead of in VM, so the PlotModel belongs to the view, not the view model. I think that is how oxyplot is "designed", since it is so tightly coupled to the view. You might be able to something similar by moving your PlotModel instance into the view and bind to that and manipulate that from VM, or just go XAML entirely.

@angularsen Hi Andreas, I have the same problem, could you please help me, it is somehow urgent .. could you please tell me how to define the plotmodel in the xaml and then to bin it to another plotmodel in the viewmodel? thanks in advance!

**Comment by Sahhary** [comment]
> PlotModel.cs

Can you please tell me, where to find this file PlotModel.cs??

**Comment by angularsen** [comment]
@Sahhary Sorry, I can't offer much more details than the explanations I have already given above. It's been many years since I last used oxyplot.
If I recall correctly, you should simply not use PlotModel together with xaml. See [my example](https://github.com/oxyplot/oxyplot/issues/497#issuecomment-253446313) for how to use it in XAML _without_ PlotModel and instead declaring the series and bindings in XAML.

**Comment by Sahhary** [comment]
@angularsen thank you very much, the problem is already solved:
https://github.com/oxyplot/oxyplot/issues/497#issuecomment-253437909

**Comment by adambennett** [comment]
Experienced this issue while using OxyPlot inside of a Carousel View (Xamarin Forms 5.0). The issue only appeared while running the app on iOS, but OxyPlot worked normally on Android without any problems. To fix this issue for iOS, we used @edvinasz solution above and replaced our instances of PlotModel with his ViewResolvingPlotModel class. Everything seems to work as expected now on both platforms.

**Comment by raffaeler** [comment]
This happens in 2.0.0 and WPF on .NET Core when I navigate back and forth on a Page containing the plot.
The Model property is binded in the ViewModel and resetting the property before loading the page does not resolve the issue.

**Comment by NeoStarkX** [comment]
I had the same problem with Oxyplot in my WPF application where the plot was in the page and when I changed the page and then came back to my page the error was thrown which was telling me **This PlotModel is already in use by some other PlotView control**. I used @edvinasz nice solution and solved my problem 😍😍

**Comment by itsme-vivek** [comment]
I had the same problem with Oxyplot in my WPF application where the plot was on the page and when I changed the page and then came back to my page the error was thrown which was telling me This PlotModel is already in use by some other PlotView control. 

Special Thanks @edvinasz's  Solution. Just Call ViewResolvingPlotModel instead of PlotModel. and your plot model works fine
