### ISSUE TITLE
Setting PositionAtZeroCrossing on one axis bleeds through to the other

### ISSUE THREAD

**Issue by dlfsdev** [oxyplot/oxyplot#737]
Not 100% sure this isn't a feature, but if the X-axis has PositionAtZeroCrossing set to true and the y-axis does not, the y-axis ticks and labels will appear on the side of the plot as expected, but there will also be an extra vertical line at x=0.

Sample WPF code:

```
<oxy:PlotView Width="300" Height="300">
   <oxy:PlotView.Axes>
      <oxy:LinearAxis Position="Left" />

      <oxy:LinearAxis Position="Bottom" PositionAtZeroCrossing="True" 
         AxislineStyle="Solid" AxislineThickness="1" />
   </oxy:PlotView.Axes>
</oxy:PlotView>
```

Result (with some data):
![image](https://cloud.githubusercontent.com/assets/8649549/12327291/ab309ada-baa3-11e5-80dd-1a2954b8adff.png)

**Comment by objorke** [comment]
I could not reproduce this error. Are you using the latest pre-release version?
I guess it was solved in #635.

Here is what I tested (in the example library):
```csharp
        [Example("#737: Wrong axis line when PositionAtZeroCrossing = true")]
        public static PlotModel WrongAxisLineWhenPositionAtZeroCrossingIsSet()
        {
            var model = new PlotModel { Title = "PositionAtZeroCrossing" };
            model.Axes.Add(
                new LinearAxis
                {
                    Position = AxisPosition.Left
                });
            model.Axes.Add(
                new LinearAxis
                {
                    Position = AxisPosition.Bottom,
                    PositionAtZeroCrossing = true,
                    AxislineStyle = LineStyle.Solid,
                    AxislineThickness = 1
                });
            var lineSeries = new LineSeries();
            lineSeries.Points.Add(new DataPoint(-10, 10));
            lineSeries.Points.Add(new DataPoint(0, -10));
            lineSeries.Points.Add(new DataPoint(10, 10));
            model.Series.Add(lineSeries);
            return model;
        }
```

**Comment by dlfsdev** [comment]
Huh. I created a new test app, grabbed the latest prelease version (2015.1.708-alpha) and then copy-pasted your exact code above with this little addition:

TheContentPresenter.Content = new PlotView { Model = model };

But I still see this:

![image](https://cloud.githubusercontent.com/assets/8649549/12393228/6082fdda-bdc2-11e5-9c84-8a0383ec5cce.png)

My test app is a WPF application, .net 4.5.

**Comment by tibel** [comment]
Thats not the latest version. It is 1.0.0-unstable1970 (compiled yesterday)
see https://www.nuget.org/packages/OxyPlot.Core/

**Comment by dlfsdev** [comment]
Hi tibel. I must be missing something. Even after uninstalling the packages I already had, running the command in your link from the package manager console fetches 2015.1.708-alpha, and the GUI built into VS doesn't show me anything more recent than that either. Is this a .net version thing (I'm targeting 4.5)? Or might I need to change some setting before it will accept a PCL?

**Comment by dlfsdev** [comment]
Ok. You're (both) right, the problem is solved in 1.0.0-unstable1970 (I had to specify the version number explicitly to get that one).
